"""Real Google Gemini Educational Summarization Verification Script.

Tests the production AI service pipeline with real Gemini calls:
1. Medium length summary on Photosynthesis
2. Short length summary on REST API Architecture
3. Detailed length summary on Operating Systems & Virtual Memory

Verifies structured JSON output, non-empty summary, key revision points,
length fidelity, and source-faithfulness.
"""

import asyncio
import json
import sys
from pathlib import Path

# Add backend directory to sys.path
backend_dir = Path(__file__).resolve().parent.parent / "backend"
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.core.config import get_settings
from app.services.ai.gemini_service import GeminiService


async def verify_real_summaries():
    print("=" * 75)
    print("EDUGENIE STEP 9 — REAL GOOGLE GEMINI SUMMARIZATION VERIFICATION")
    print("=" * 75)

    settings = get_settings()
    if not settings.is_gemini_configured:
        print("[ERROR] GEMINI_API_KEY is not configured in .env.")
        sys.exit(1)

    print(f"[OK] Model configured: {settings.GEMINI_MODEL}")
    print("[OK] GEMINI_API_KEY is configured (hidden).")

    service = GeminiService(settings=settings)

    test_cases = [
        {
            "name": "Photosynthesis",
            "length": "medium",
            "content": (
                "Photosynthesis is the fundamental biological process through which green plants, algae, and certain cyanobacteria "
                "convert light energy into chemical energy stored in carbohydrates like glucose. This vital reaction takes place "
                "inside specialized cellular organelles called chloroplasts, which are rich in chlorophyll pigments that absorb blue "
                "and red light while reflecting green. During the light-dependent reactions within thylakoid membranes, absorbed photons "
                "drive the photolysis of water molecules, yielding protons, electrons, and releasing molecular oxygen into the atmosphere. "
                "The resulting energy carriers, ATP and NADPH, are then transferred to the fluid stroma where the light-independent "
                "Calvin cycle fixes atmospheric carbon dioxide into glyceraldehyde 3-phosphate, sustaining almost all terrestrial food webs."
            ),
        },
        {
            "name": "REST API Architecture",
            "length": "short",
            "content": (
                "Representational State Transfer (REST) is an architectural style for distributed hypermedia systems first formulated "
                "by Roy Fielding. REST systems are characterized by a client-server relationship, stateless communication where each "
                "request contains all context necessary to process it, and standard uniform interfaces utilizing HTTP methods. In REST, "
                "resources are uniquely identified by URIs, while standard HTTP verbs (GET, POST, PUT, DELETE, PATCH) define operations. "
                "GET requests are safe and idempotent, while POST creates new subordinate resources. Caching mechanisms can be applied "
                "to responses to improve network efficiency and scalability."
            ),
        },
        {
            "name": "Operating Systems & Virtual Memory",
            "length": "detailed",
            "content": (
                "An operating system (OS) is essential system software that manages computer hardware and software resources, providing "
                "common services for application programs. Core functions include processor management through CPU scheduling algorithms "
                "such as Round Robin, Shortest Job First, and Multi-Level Feedback Queues. The OS coordinates memory allocation through "
                "virtual memory architectures, paging, and segmentation, preventing processes from interfering with each other's address "
                "spaces. In a paged virtual memory system, the memory management unit (MMU) translates virtual addresses generated by the CPU "
                "into physical addresses using page tables. When a requested page is not in physical RAM, a page fault exception is triggered, "
                "prompting the kernel to fetch the page from backing store via page replacement algorithms like Least Recently Used (LRU) or Clock."
            ),
        },
    ]

    all_passed = True

    for i, test in enumerate(test_cases, 1):
        print(f"\n--- [TEST {i}/3]: Topic='{test['name']}', Length='{test['length']}' ---")
        try:
            resp = await service.summarize_text(
                content=test["content"],
                length=test["length"],
            )

            print(f"[SUCCESS] Length: {resp.length}")
            print(f"          Model: {resp.model}")
            print(f"          Summary chars: {resp.summary_length_chars}")
            print(f"          Key points: {len(resp.key_points)}")
            print(f"          Request ID: {resp.request_id}")
            print(f"\n[SUMMARY PREVIEW]:\n{resp.summary}")
            print("\n[KEY REVISION POINTS]:")
            for idx, pt in enumerate(resp.key_points, 1):
                print(f"  {idx}. {pt}")

            # Assertions
            assert resp.summary, "Summary must not be empty"
            assert len(resp.key_points) > 0, "Must have at least 1 key point"
            assert resp.length == test["length"], f"Length must match {test['length']}"
            assert resp.request_id, "Request ID must be present"

            print(f"[VALIDATION PASSED] All assertions satisfied for {test['name']}")

        except Exception as exc:
            print(f"[FAILED] Error generating summary for {test['name']}: {exc}")
            all_passed = False

    print("\n" + "=" * 75)
    if all_passed:
        print("[ALL REAL GEMINI SUMMARIZATION TESTS PASSED SUCCESSFULLY]")
    else:
        print("[FAILURES DETECTED IN REAL GEMINI TESTS]")
    print("=" * 75)


if __name__ == "__main__":
    asyncio.run(verify_real_summaries())
